# Generated by Django 4.2.6 on 2023-11-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_register_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.BigIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=8),
        ),
    ]
