# Generated by Django 4.2.6 on 2023-11-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_register_contact_alter_register_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Prefer not to say', 'Prefer not to say')], max_length=100),
        ),
    ]
